# Generated by Django 6.0.3 on 2026-04-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=20)),
                ("descricao", models.TextField()),
                ("semestres", models.PositiveIntegerField()),
                ("creditos", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=20)),
                ("ano", models.PositiveIntegerField()),
                ("semestre", models.PositiveIntegerField()),
                ("ects", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                ("docente", models.CharField(max_length=150)),
                ("link_docente", models.URLField()),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
