# Generated by Django 6.0.3 on 2026-04-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_competencia_tag_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autores", models.CharField(max_length=200)),
                ("ano", models.PositiveIntegerField()),
                ("resumo", models.TextField()),
                ("orientadores", models.CharField(max_length=200)),
                ("interesse", models.PositiveIntegerField(help_text="Escala de 1 a 5")),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                ("imagem", models.ImageField(upload_to="projetos/")),
                ("data", models.DateField()),
                ("github_url", models.URLField()),
                ("video_demo_url", models.URLField(blank=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tag"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
