# Generated by Django 6.0.3 on 2026-04-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_tfc_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("entidade", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="formacoes/"),
                ),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("foto", models.ImageField(upload_to="making_of/")),
                ("ferramentas_ia", models.TextField(blank=True)),
                ("descricao", models.TextField()),
                ("erros", models.TextField(blank=True)),
                ("correcao", models.TextField(blank=True)),
                ("justificacao", models.TextField(blank=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makingofs",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
    ]
