# Generated by Django 6.0.3 on 2026-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_formacao_makingof"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="email",
            field=models.EmailField(default="test@test.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(
                default="Licenciatura em Informatica de Gestão", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
