# Generated by Django 6.0.3 on 2026-04-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_tfc_email_tfc_imagem_tfc_licenciatura_tfc_pdf_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tfc",
            old_name="resumo",
            new_name="sumario",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="interesse",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="orientadores",
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(default="desconhecido", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="parceria",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias_usadas",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="pdf",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tfc",
            name="rating",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=250),
        ),
    ]
