# Generated by Django 6.0.3 on 2026-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_rename_resumo_tfc_sumario_remove_tfc_interesse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docente",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="link_docente",
            field=models.URLField(blank=True),
        ),
    ]
