# Generated by Django 6.0.3 on 2026-04-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_unidadecurricular_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.CharField(max_length=20),
        ),
    ]
