# Generated by Django 6.0.3 on 2026-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_unidadecurricular_semestre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="github_url",
            field=models.URLField(blank=True),
        ),
    ]
