# Generated by Django 6.0.3 on 2026-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_projeto_github_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("link_pagina", models.URLField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="orientador",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="tecnologias_usadas",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="docente",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="link_docente",
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientador_texto",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="tfcs", to="portfolio.tecnologia"
            ),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="nivel",
            field=models.PositiveIntegerField(help_text="Escala de 1 a 5"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="entidade",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="sigla",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tag",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="parceria",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="sigla",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.ManyToManyField(
                blank=True, related_name="tfcs_orientados", to="portfolio.docente"
            ),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="unidades_curriculares", to="portfolio.docente"
            ),
        ),
    ]
