# Generated by Django 6.0.3 on 2026-04-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_docente_remove_tfc_orientador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="interesse",
            field=models.PositiveIntegerField(
                blank=True, help_text="Escala de 1 a 5", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="link_oficial",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
        ),
    ]
