# Generated by Django 6.0.3 on 2026-04-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_tecnologia_interesse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="imagem",
        ),
    ]
